CREATE TABLE IF NOT EXISTS state (id TEXT PRIMARY KEY, data TEXT NOT NULL, updated INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS pair (code TEXT PRIMARY KEY, key TEXT NOT NULL, expires INTEGER NOT NULL);
